app:
    resource: '@AppBundle/Controller'
    type: annotation

api_articles:
    type:     rest
    prefix: api
    resource: AppBundle\Controller\ApiArticlesController

logout:
    path: /logout

index:
    path:     /index
    defaults: { _controller: AppBundle:Default:index }        